<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="BlazarTech.QueryableValues.SqlServer" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
    <PackageReference Include="PozitronDev.Convert" />
    <PackageReference Include="MediatR" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\PozitronDev.SharedKernel\PozitronDev.SharedKernel.csproj" />
  </ItemGroup>
  
</Project>
